version: '3'

includes:
  uv: .task/taskfiles/Taskfile-uv.yml
  misc: 
    taskfile: .task/taskfiles/Taskfile-misc.yml
    flatten: true

vars:
  UV: "{{.TASKFILE_DIR}}/.tmp/bin/uv"
  IMAGE: "docker.io/library/dunamai"

tasks:

  version:
    desc: "Compute the version of the project"
    deps:
      - uv:sync
    silent: true
    cmds:
      - "{{.UV}} run dunamai from any --style semver |sed 's/+/_/g'"

  clean:
    desc: "Clean the repository"
    deps:
      - uv:clean

  install:
    desc: "Install the venv" 
    deps:
      - uv:sync

  build:
    desc: "Build the docker image"
    deps:
      - uv:sync
    cmds:
      - docker build -t {{.IMAGE}} .

  test:
    desc: "Test the docker image"
    deps:
      - uv:sync
    cmds:
      - docker run --rm -v `pwd`:/code {{.IMAGE}} from git --path /code
