name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

env:
  IMAGE: ghcr.io/fabien-marty/dunamai-docker

jobs:
  main_ci:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # we need this because fetch-tags=true and because of a GHA bug: https://github.com/actions/checkout/issues/1471
          fetch-tags: true
      - name: Set up Python # not used for smartlink itself
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" 
      - name: Compute version
        id: version
        run: |
          export VERSION=`make version |awk -F '.' '{print $1"."$2"."$3}' |awk -F '-' '{print $1;}'`
          export VERSION2=`echo ${VERSION} |awk -F '.' '{print $1"."$2}'`
          echo "### Version: ${VERSION} 🚀" >>${GITHUB_STEP_SUMMARY}
          echo "### Version2: ${VERSION2} 🚀" >>${GITHUB_STEP_SUMMARY}
          echo "version=${VERSION}" >>${GITHUB_OUTPUT}
          echo "version2=${VERSION2}" >>${GITHUB_OUTPUT}
          echo "VERSION=${VERSION}"
          echo "VERSION2=${VERSION2}"
          if test "${{ github.event_name }}/${{ github.ref }}" = "push/refs/heads/main"; then
            echo "tags=${{ env.IMAGE }}:latest" >>${GITHUB_OUTPUT}
          else
            echo "tags=${{ env.IMAGE }}:${VERSION2}" >>${GITHUB_OUTPUT}
          fi
      - name: Tests
        run: |
          make test
      - name: Check dirty
        run: |
          make no-dirty
      - name: Clean
        run: |
          make clean
      - name: Check dirty (after clean)
        run: |
          make no-dirty
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
           images: ${{ env.IMAGE }}
      - name: Login to GitHub Container Registry
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.version.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}